import { defineConfig } from "vite-plus";

export default defineConfig({
  staged: {
    "*": "vp check --fix",
    // oxfmt, then one style utility per line (packages/core/scripts/fmt-html.ts)
    "*.html": "node packages/core/scripts/fmt-html.ts",
  },
  fmt: {
    // Generated by packages/core/scripts/generate-utilities.ts; their freshness
    // test pins the generator's bytes, so the formatter must leave them alone.
    ignorePatterns: [
      "packages/core/src/base/_breakpoints.css",
      "packages/core/src/base/_properties.css",
      "packages/core/src/base/_properties-*.css",
      "packages/core/src/base/_utilities-*.css",
      "packages/core/editor/*.json",
    ],
    overrides: [
      // Keep style="" exactly as authored (one utility per line stays one per line).
      { files: ["**/*.html"], options: { embeddedLanguageFormatting: "off" } },
    ],
  },
  lint: {
    jsPlugins: [{ name: "vite-plus", specifier: "vite-plus/oxlint-plugin" }],
    rules: { "vite-plus/prefer-vite-plus-imports": "error" },
    options: { typeAware: true, typeCheck: true },
  },
  run: {
    cache: true,
  },
});
