import { defineConfig } from "vite-plus";

export default defineConfig({
  staged: {
    "*": "vp check --fix",
    // style utilities in cascade order, one per line (zazz/style-format, eslint.config.ts)
    "*.html": "eslint --fix",
  },
  fmt: {
    // Generated by packages/core/scripts/generate-utilities.ts; their freshness
    // test pins the generator's bytes, so the formatter must leave them alone.
    ignorePatterns: [
      "packages/core/src/base/_breakpoints.css",
      "packages/core/src/base/_properties.css",
      "packages/core/src/base/_properties-*.css",
      "packages/core/src/base/_utilities-*.css",
      "packages/core/editor/*.json",
      // Generated by packages/vscode/scripts/generate-*.ts; their tests compare bytes.
      "packages/vscode/snippets/zazz.code-snippets",
      "packages/vscode/syntaxes/zazz.injection.tmLanguage.json",
      "packages/vscode/emmet/snippets.json",
    ],
    overrides: [
      // Keep style="" exactly as authored (one utility per line stays one per line).
      { files: ["**/*.html"], options: { embeddedLanguageFormatting: "off" } },
    ],
  },
  lint: {
    jsPlugins: [{ name: "vite-plus", specifier: "vite-plus/oxlint-plugin" }],
    rules: { "vite-plus/prefer-vite-plus-imports": "error" },
    options: { typeAware: true, typeCheck: true },
  },
  run: {
    cache: true,
  },
});
