/**
 * @fileoverview Generates the utilities layer from `src/base/utilities.ts`.
 * Pure functions take explicit inputs and return CSS text so
 * tests can pin literals; `main()` writes the files into `src/base/`.
 *
 * Usage: `vp run generate` (or `node scripts/generate-utilities.ts`). The
 * generated files are committed; `generate-utilities.test.ts` fails when they
 * are stale.
 */

import { writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import {
  BORDER_SIDES,
  type Breakpoint,
  BREAKPOINT_REM,
  BREAKPOINTS,
  type Family,
  isState,
  type Utility,
  UTILITIES,
  PSEUDO_ONLY,
  PSEUDO_SIDES,
  type PseudoSide,
  STATE_SELECTORS,
  STATES,
  tiersOf,
} from "../src/base/utilities.ts";
import { TAG_FORMS } from "../src/manifest.ts";

const BANNER =
  "/* Generated by scripts/generate-utilities.ts from src/base/utilities.ts — do not edit. */\n";

function register(name: string, syntax = '"*"', initial?: string): string {
  const init = initial === undefined ? "" : ` initial-value: ${initial};`;
  return `@property --${name} { syntax: ${syntax}; inherits: false;${init} }\n`;
}

/** The page-container flag for one breakpoint: registration plus the body setter. */
export function breakpointFlag(bp: Breakpoint, rem: number): string {
  return [
    `@property --cqi-${bp} {`,
    `  syntax: "true | false";`,
    `  inherits: true;`,
    `  initial-value: false;`,
    `}`,
    `@container html (width >= ${rem}rem) {`,
    `  body {`,
    `    --cqi-${bp}: true;`,
    `  }`,
    `}`,
    ``,
  ].join("\n");
}

/** A utility's base registrations: the utility, its base layer variable, its resolver, and the dual pair. */
export function registrations(utility: Utility): string {
  const n = utility.name;
  let out = register(n) + register(`_${n}`) + register(`_${n}-resolved`);
  if (utility.mode === "dual") {
    out += register(`_${n}-len`, '"<length-percentage>"', "0px");
    out += register(`_${n}-num`, '"<number>"', "0");
  }
  if (utility.emit === "border") {
    out += register(`_${n}-len`, '"<length>"', "0px");
    out += register(`_${n}-num`, '"<number>"', "0");
    out += register(`_${n}-is-len`, '"<number>"', "0");
    out += register(`_${n}-is-num`, '"<number>"', "0");
    out += register(`_${n}-clr`, '"<color>"', "transparent");
    out += register(`_${n}-w`) + register(`_${n}-c`);
  }
  return out;
}

/** One tier of a utility: the modifier utility and its layer variable; states add the group twin. */
export function tierRegistrations(utility: Utility, tier: string): string {
  let out = register(`${utility.name}--${tier}`) + register(`_${utility.name}-${tier}`);
  if (isState(tier)) {
    out += register(`group-${utility.name}--${tier}`) + register(`_${utility.name}-g-${tier}`);
  }
  return out;
}

/** The precedence chain over a utility's layer variables: `tiers` highest-precedence first, ending in `end`. */
export function chain(name: string, tiers: readonly string[], end: string): string {
  return tiers.reduceRight((inner, tier) => `var(--_${name}-${tier}, ${inner})`, end);
}

/**
 * The `:is()` list of every keyword form of every utility in a family, at the base
 * and at each tier. Exact strings, so `--overflow: auto` never matches.
 */
export function keywordGates(utilities: readonly Utility[], tiers: readonly string[]): string {
  const forms: string[] = [];
  for (const utility of utilities) {
    for (const keyword of utility.keywords ?? []) {
      forms.push(`[style*="--${utility.name}: ${keyword}"]`);
      for (const tier of tiers) forms.push(`[style*="--${utility.name}--${tier}: ${keyword}"]`);
    }
  }
  return forms.length === 0 ? "" : `:is(${forms.join(", ")})`;
}

/**
 * The resolver and the base rule for one utility. State tiers chain own states,
 * then group states. With a keyword `gate`, a raw twin follows the dual rule,
 * gated on the keyword forms; same specificity and later in source, so it
 * overrides the dual emission on those elements.
 */
export function baseRule(utility: Utility, tiers: readonly string[], gate = ""): string {
  const n = utility.name;
  const stateTiers = tiers.some(isState);
  // Precedence: own states, then group states (both highest first); breakpoints descend.
  const chainTiers = stateTiers
    ? [...tiers, ...tiers.map((tier) => `g-${tier}`)]
    : [...tiers].reverse();
  const gates = [`[style*="--${n}:"]`, `[style*="--${n}--"]`];
  if (stateTiers) gates.push(`[style*="--group-${n}--"]`);
  const lines = [
    `:where(${gates.join(", ")}) {`,
    `  --_${n}-resolved: ${chain(n, chainTiers, `var(--_${n})`)};`,
    `}`,
    `:where([style*="--${n}:"]) {`,
    `  --_${n}: var(--${n});`,
  ];
  if (utility.emit === "border") {
    lines.push(...borderChannels(n).map((d) => `  ${d}`));
  } else if (utility.mode === "dual") {
    lines.push(`  --_${n}-len: var(--_${n}-resolved);`, `  --_${n}-num: var(--_${n}-resolved);`);
    for (const property of utility.properties) {
      lines.push(`  ${property}: calc(var(--_${n}-len) + var(--_${n}-num) * var(--spacing));`);
    }
  } else {
    const extra = companions(utility);
    lines.push(...extra.before.map((d) => `  ${d}`));
    for (const property of utility.properties) {
      lines.push(`  ${property}: ${emission(utility, `var(--_${n}-resolved)`)};`);
    }
    lines.push(...extra.after.map((d) => `  ${d}`));
  }
  lines.push(`}`);
  if (gate) {
    lines.push(
      `:where([style*="--${n}:"]${gate}) {`,
      `  --_${n}: var(--${n});`,
      ...utility.properties.map((property) => `  ${property}: var(--_${n}-resolved);`),
      `}`,
    );
  }
  lines.push(``);
  return lines.join("\n");
}

/**
 * The border shorthand's channels. Each typed channel takes the
 * resolved value; one whose syntax the value does not match falls back to its
 * initial value at computed-value time, so exactly one of the flags is 1 for a
 * number or a length, and both are 0 for a color.
 */
function borderChannels(n: string): string[] {
  const resolved = `var(--_${n}-resolved)`;
  const isColor = `(1 - var(--_${n}-is-num) - var(--_${n}-is-len))`;
  return [
    `--_${n}-len: ${resolved};`,
    `--_${n}-num: ${resolved};`,
    `--_${n}-is-len: calc(sin(atan2(${resolved}, 1px)) * 0 + 1);`,
    `--_${n}-is-num: calc(${resolved} * 0 + 1);`,
    `--_${n}-clr: ${resolved};`,
    `--_${n}-w: calc(abs(var(--_${n}-len)) + abs(var(--_${n}-num)) * 1px + ${isColor} * 1px);`,
    `--_${n}-c: color-mix(in oklch, var(--_${n}-clr) calc(${isColor} * 100%), var(--color-border));`,
  ];
}

/**
 * One rule per physical side, gated on any shorthand covering it.
 * Precedence: the side longhand, the all-sides longhand, then the side, axis,
 * and all-sides shorthands. Style defaults to solid unless `--border-style` is set.
 */
export function borderSideRules(): string {
  const out: string[] = [];
  for (const { side, property, shorthands } of BORDER_SIDES) {
    const fallback = (part: "w" | "c") =>
      shorthands.reduceRight<string>(
        (inner, name) => (inner ? `var(--_${name}-${part}, ${inner})` : `var(--_${name}-${part})`),
        "",
      );
    const longhand = (kind: "width" | "color", part: "w" | "c") =>
      `var(--_border-${side}-${kind}-resolved, var(--_border-${kind}-resolved, ${fallback(part)}))`;
    out.push(
      `:where(${[...shorthands]
        .reverse()
        .map((name) => `[style*="--${name}:"]`)
        .join(", ")}) {`,
      `  ${property}-width: ${longhand("width", "w")};`,
      `  ${property}-style: var(--_border-style-resolved, solid);`,
      `  ${property}-color: ${longhand("color", "c")};`,
      `}`,
    );
  }
  return out.join("\n") + "\n";
}

/** The value a utility's property is set to, given the resolved value expression. */
function emission(utility: Utility, resolved: string): string {
  if (utility.emit === "repeat") return `repeat(${resolved}, minmax(0, 1fr))`;
  if (utility.emit === "grid-fit") return `repeat(auto-fit, minmax(min(${resolved}, 100%), 1fr))`;
  if (utility.emit === "bg")
    return `oklch(from ${resolved} l c h / calc(alpha * var(--_bg-alpha-resolved, 1)))`;
  return resolved;
}

/** Declarations that ride along with a utility's emission (compound utilities). */
function companions(utility: Utility): { before: string[]; after: string[] } {
  if (utility.emit === "line-clamp") {
    return {
      before: ["display: -webkit-box;", "-webkit-box-orient: vertical;"],
      after: ["overflow: hidden;"],
    };
  }
  return { before: [], after: [] };
}

/**
 * The no-base rule for an allowlisted utility: gated on any tier, the
 * chain ends in the CSS initial value as a literal, primitives excluded.
 */
export function noBaseRule(utility: Utility, tagForms: readonly string[]): string {
  const n = utility.name;
  if (utility.noBase === undefined) return "";
  const excluded = ["[data-ui]", ...tagForms, ...(utility.noBaseExclude ?? [])].join(", ");
  const resolved = `var(--_${n}-resolved, ${utility.noBase})`;
  const body =
    utility.mode === "dual"
      ? [
          `  --_${n}-len: ${resolved};`,
          `  --_${n}-num: ${resolved};`,
          ...utility.properties.map(
            (property) =>
              `  ${property}: calc(var(--_${n}-len) + var(--_${n}-num) * var(--spacing));`,
          ),
        ]
      : utility.properties.map((property) => `  ${property}: ${emission(utility, resolved)};`);
  return [
    `:where(:is([style*="--${n}:"], [style*="--${n}--"], [style*="--group-${n}--"]):not(${excluded})) {`,
    ...body,
    `}`,
    ``,
  ].join("\n");
}

/** One tier's setter: gated generically, copies every utility of that tier into its layer variable. */
export function setterRule(tier: string, utilities: readonly Utility[]): string {
  const inTier = utilities.filter((utility) => tiersOf(utility).includes(tier));
  const indent = (lines: string[], depth: number) => lines.map((line) => " ".repeat(depth) + line);
  if (isState(tier)) {
    const { pseudo, media } = STATE_SELECTORS[tier];
    const own = [
      `:where([style*="--${tier}:"]${pseudo}) {`,
      ...inTier.map((utility) => `  --_${utility.name}-${tier}: var(--${utility.name}--${tier});`),
      `}`,
    ];
    const group = [
      `:where([data-ui~="group"]${pseudo} [style*="--group-"]) {`,
      ...inTier.map(
        (utility) => `  --_${utility.name}-g-${tier}: var(--group-${utility.name}--${tier});`,
      ),
      `}`,
    ];
    const body = [...own, ...group];
    return (media ? [`@media ${media} {`, ...indent(body, 2), `}`] : body).concat("").join("\n");
  }
  const body = [
    `:where([style*="--${tier}:"]) {`,
    ...inTier.map((utility) => `  --_${utility.name}-${tier}: var(--${utility.name}--${tier});`),
    `}`,
  ];
  return [`@container style(--cqi-${tier}: true) {`, ...indent(body, 2), `}`, ``].join("\n");
}

/**
 * The effects composite: ring and shadow share one `box-shadow`,
 * behind the `--_focus-ring` a primitive publishes on `:focus-visible`. Every
 * chain in it already ends in a literal, so the composite is also the
 * no-base rule for these utilities: a second copy gated on any tier, primitives
 * excluded.
 */
export function compositeRule(utilities: readonly Utility[], tagForms: readonly string[]): string {
  const names = new Set(utilities.map((utility) => utility.name));
  const RING = ["shadow", "ring", "ring-color", "ring-offset", "ring-offset-color"];
  if (!RING.some((name) => names.has(name))) return "";
  const gate = (prefix: string, suffix: string) =>
    `:is(${RING.map((name) => `[style*="--${prefix}${name}${suffix}"]`).join(", ")})`;
  const excluded = ["[data-ui]", ...tagForms].join(", ");
  const offset = "var(--_ring-offset-resolved, 0px)";
  const emission = `  box-shadow: var(--_focus-ring, 0 0 #0000), 0 0 0 ${offset} var(--_ring-offset-color-resolved, transparent), 0 0 0 calc(${offset} + var(--_ring-resolved, 0px)) var(--_ring-color-resolved, var(--color-ring)), var(--_shadow-resolved, 0 0 #0000);`;
  return [
    `:where(${gate("", ":")}) {`,
    emission,
    `}`,
    `:where(:is(${gate("", "--")}, ${gate("group-", "--")}):not(${excluded})) {`,
    emission,
    `}`,
    ``,
  ].join("\n");
}

/**
 * A pseudo-element rule: exact gate on `--<side>-<utility>`, read
 * straight from the (unregistered, inherited) utility on the pseudo-element.
 */
export function pseudoRule(utility: Utility, side: PseudoSide): string {
  if (!utility.pseudo || utility.emit === "none") return "";
  const n = `${side}-${utility.name}`;
  const lines = [`:where([style*="--${n}:"])::${side} {`];
  if (utility.mode === "dual") {
    lines.push(`  --_${n}-len: var(--${n});`, `  --_${n}-num: var(--${n});`);
    for (const property of utility.properties) {
      lines.push(`  ${property}: calc(var(--_${n}-len) + var(--_${n}-num) * var(--spacing));`);
    }
  } else {
    const value =
      utility.emit === "bg"
        ? `oklch(from var(--${n}) l c h / calc(alpha * var(--${side}-bg-alpha, 1)))`
        : `var(--${n})`;
    for (const property of utility.properties) lines.push(`  ${property}: ${value};`);
  }
  lines.push(`}`, ``);
  return lines.join("\n");
}

/** Typed pairs for dual utilities on pseudo-elements; declared on the pseudo-element itself. */
function pseudoRegistrations(utility: Utility): string {
  if (!utility.pseudo || utility.mode !== "dual") return "";
  return PSEUDO_SIDES.map(
    (side) =>
      register(`_${side}-${utility.name}-len`, '"<length-percentage>"', "0px") +
      register(`_${side}-${utility.name}-num`, '"<number>"', "0"),
  ).join("");
}

/** `_breakpoints.css`: the width tokens and the seven flags. */
function breakpointsFile(): string {
  const tokens = BREAKPOINTS.map((bp) => `    --breakpoint-${bp}: ${BREAKPOINT_REM[bp]}rem;`).join(
    "\n",
  );
  return [
    BANNER,
    "/* Breakpoint tokens — the one place the widths live. */",
    "@layer variables {",
    "  :root {",
    tokens,
    "  }",
    "}",
    "",
    "/* Page-container flags: set once on body from the html container; every",
    "   descendant inherits them and style-queries its parent. */",
    ...BREAKPOINTS.map((bp) => breakpointFlag(bp, BREAKPOINT_REM[bp])),
  ].join("\n");
}

function familyFile(
  family: Family,
  utilities: readonly Utility[],
  tagForms: readonly string[],
): string {
  const gate = keywordGates(utilities, tiersOf(utilities[0]!));
  const rules = utilities
    .map(
      (utility) =>
        baseRule(utility, tiersOf(utility), utility.keywords ? gate : "") +
        noBaseRule(utility, tagForms),
    )
    .concat(compositeRule(utilities, tagForms))
    .concat(utilities.some((utility) => utility.emit === "border") ? [borderSideRules()] : [])
    .join("\n")
    .replace(/^(?=.)/gm, "  ");
  return `${BANNER}\n/* ${family} family: one resolver and one base rule per utility. */\n@layer zazz.utilities {\n${rules}}\n`;
}

/** Every generated file, keyed by its name under `src/base/`. */
export function generate(
  utilities: readonly Utility[] = UTILITIES,
  tagForms: readonly string[] = TAG_FORMS,
): Map<string, string> {
  const files = new Map<string, string>();
  files.set("_breakpoints.css", breakpointsFile());
  files.set(
    "_properties.css",
    `${BANNER}\n/* Base registrations: every utility, its layer variable, resolver, and dual pair. */\n${utilities.map(registrations).join("")}\n/* Typed pairs for dual utilities on pseudo-elements (the --before- and --after- utilities themselves are never registered). */\n${utilities.map(pseudoRegistrations).join("")}\n/* Published by primitives on :focus-visible; every box-shadow emission includes it first. */\n${register("_focus-ring")}`,
  );
  for (const tier of [...BREAKPOINTS, ...STATES]) {
    const inTier = utilities.filter((utility) => tiersOf(utility).includes(tier));
    files.set(
      `_properties-${tier}.css`,
      `${BANNER}\n/* ${tier} tier registrations: the modifier utility and its layer variable. */\n${inTier.map((utility) => tierRegistrations(utility, tier)).join("")}`,
    );
  }
  for (const tier of [...BREAKPOINTS, ...STATES]) {
    const when = isState(tier) ? "while the element is in that state" : "while the flag is true";
    files.set(
      `_utilities-tier-${tier}.css`,
      `${BANNER}\n/* ${tier} tier setter: copies every --<utility>--${tier} into its layer variable ${when}. */\n@layer zazz.utilities {\n${setterRule(tier, utilities).replace(/^(?=.)/gm, "  ")}}\n`,
    );
  }
  const families = [...new Set(utilities.map((utility) => utility.family))];
  for (const family of families) {
    files.set(
      `_utilities-${family}.css`,
      familyFile(
        family,
        utilities.filter((utility) => utility.family === family),
        tagForms,
      ),
    );
  }
  const pseudo = [...utilities, ...PSEUDO_ONLY]
    .flatMap((utility) => PSEUDO_SIDES.map((side) => pseudoRule(utility, side)))
    .filter(Boolean)
    .join("\n")
    .replace(/^(?=.)/gm, "  ");
  files.set(
    "_utilities-pseudo.css",
    `${BANNER}\n/* Pseudo-element utilities: --before- and --after- forms, exact gates, no tiers. */\n@layer zazz.utilities {\n${pseudo}}\n`,
  );
  return files;
}

export function main(): void {
  const base = join(dirname(fileURLToPath(import.meta.url)), "..", "src", "base");
  for (const [file, text] of generate()) {
    writeFileSync(join(base, file), text);
    console.log(`wrote src/base/${file}`);
  }
}

if (import.meta.main) main();
