/**
 * @fileoverview Generates the utilities layer from `src/base/utilities.ts`.
 * Pure functions take explicit inputs and return CSS text so
 * tests can pin literals; `main()` writes the files into `src/base/`.
 *
 * Usage: `vp run generate` (or `node scripts/generate-utilities.ts`). The
 * generated files are committed; `generate-utilities.test.ts` fails when they
 * are stale.
 */

import { readFileSync, readdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import {
  BORDER_SIDES,
  type Breakpoint,
  BREAKPOINT_CH,
  LAYOUT_REM,
  BREAKPOINTS,
  DISPLAY_SHORTHANDS,
  type Family,
  GRADIENT_TYPES,
  hasGroup,
  isState,
  type Utility,
  UTILITIES,
  PSEUDO_ONLY,
  PSEUDO_SIDES,
  type PseudoSide,
  STUCK_STATE,
  STATE_SELECTORS,
  STATES,
  tiersOf,
} from "../src/base/utilities.ts";
import { TAG_FORMS } from "../src/manifest.ts";

const BANNER =
  "/* Generated by scripts/generate-utilities.ts from src/base/utilities.ts — do not edit. */\n";

function register(name: string, syntax = '"*"', initial?: string, inherits = false): string {
  const init = initial === undefined ? "" : ` initial-value: ${initial};`;
  return `@property --${name} { syntax: ${syntax}; inherits: ${inherits};${init} }\n`;
}

/**
 * The query a breakpoint tier sits in: the nearest ancestor inline-size
 * container (`ch` resolves against that container's font). html, body, and
 * the sectioning elements are containers by default; `data-ui="container"`
 * makes any element one.
 */
export function breakpointQuery(bp: Breakpoint): string {
  return `@container (width >= ${BREAKPOINT_CH[bp]}ch)`;
}

/** A utility's base registrations: the utility, its base layer variable, its resolver, and the dual pair. */
export function registrations(utility: Utility): string {
  const n = utility.name;
  let out = register(n) + register(`_${n}`) + register(`_${n}-resolved`);
  if (utility.mode === "dual") {
    out += register(`_${n}-len`, '"<length-percentage>"', "0px");
    out += register(`_${n}-num`, '"<number>"', "0");
  }
  if (utility.emit === "border") {
    out += register(`_${n}-len`, '"<length>"', "0px");
    out += register(`_${n}-num`, '"<number>"', "0");
    out += register(`_${n}-is-len`, '"<number>"', "0");
    out += register(`_${n}-is-num`, '"<number>"', "0");
    out += register(`_${n}-clr`, '"<color>"', "transparent");
    const inherits = utility.inherits === true;
    out += register(`_${n}-w`, undefined, undefined, inherits);
    out += register(`_${n}-c`, undefined, undefined, inherits);
  }
  return out;
}

/** One tier of a utility: the modifier utility and its layer variable; states add the group twin. */
export function tierRegistrations(utility: Utility, tier: string): string {
  let out = register(`${utility.name}--${tier}`) + register(`_${utility.name}-${tier}`);
  if (isState(tier) && hasGroup(tier)) {
    out += register(`group-${utility.name}--${tier}`) + register(`_${utility.name}-g-${tier}`);
  }
  return out;
}

/** The precedence chain over a utility's layer variables: `tiers` highest-precedence first, ending in `end`. */
export function chain(name: string, tiers: readonly string[], end: string): string {
  return tiers.reduceRight((inner, tier) => `var(--_${name}-${tier}, ${inner})`, end);
}

/**
 * The resolver and the base rule for one utility. State tiers chain the starting
 * state, own states, group states, then the scroll state.
 */
export function baseRule(utility: Utility, tiers: readonly string[]): string {
  const n = utility.name;
  const stateTiers = tiers.some(isState);
  // Precedence: the starting state (highest: it only exists in the starting style),
  // own pseudo states, their group forms, the stuck state, then breakpoints descending
  // (a state beats a breakpoint, as in Tailwind), then the base.
  const pseudoStates = tiers.filter((tier) => isState(tier) && hasGroup(tier));
  const flagged = (flag: "starting" | "stuck") =>
    tiers.filter((tier) => isState(tier) && STATE_SELECTORS[tier][flag]);
  const breakpoints = tiers.filter((tier) => !isState(tier)).reverse();
  const chainTiers = stateTiers
    ? [
        ...flagged("starting"),
        ...pseudoStates,
        ...pseudoStates.map((tier) => `g-${tier}`),
        ...flagged("stuck"),
        ...breakpoints,
      ]
    : breakpoints;
  const gates = [`[style*="--${n}:"]`, `[style*="--${n}--"]`];
  if (stateTiers) gates.push(`[style*="--group-${n}--"]`);
  const lines = [
    `:where(${gates.join(", ")}) {`,
    `  --_${n}-resolved: ${chain(n, chainTiers, `var(--_${n})`)};`,
    `}`,
    `:where([style*="--${n}:"]) {`,
    `  --_${n}: var(--${n});`,
  ];
  if (utility.emit === "border") {
    lines.push(...borderChannels(n).map((d) => `  ${d}`));
  } else if (utility.mode === "dual") {
    lines.push(`  --_${n}-len: var(--_${n}-resolved);`, `  --_${n}-num: var(--_${n}-resolved);`);
    for (const property of utility.properties) {
      lines.push(`  ${property}: calc(var(--_${n}-len) + var(--_${n}-num) * var(--spacing));`);
    }
  } else {
    const extra = companions(utility);
    lines.push(...extra.before.map((d) => `  ${d}`));
    for (const property of utility.properties) {
      lines.push(`  ${property}: ${emission(utility, `var(--_${n}-resolved)`)};`);
    }
    lines.push(...extra.after.map((d) => `  ${d}`));
  }
  lines.push(`}`, ``);
  return lines.join("\n");
}

/**
 * Keyword rules for a utility with keywords (until CSS `if()` can branch per
 * value). The typed rule above cannot carry a keyword, so: one rule emits a
 * base keyword as written; then, per breakpoint in ascending order inside its
 * flag query, a restore rule re-emits the typed value when that tier is set and
 * a keyword rule emits it as written when that tier holds a keyword. Same
 * (zero) specificity and later in source, so the highest active tier wins and
 * numbers and keywords mix freely across tiers (`--w: 4; --w--md: auto`).
 */
export function keywordRules(
  utility: Utility,
  tiers: readonly string[],
  primitives: readonly string[],
): string {
  const n = utility.name;
  const keywords = utility.keywords ?? [];
  if (keywords.length === 0) return "";
  if (tiers.some(isState)) throw new Error(`--${n}: keywords need a breakpoint family`);
  const forms = (tier: string) =>
    `:is(${keywords.map((keyword) => `[style*="--${n}${tier ? `--${tier}` : ""}: ${keyword}"]`).join(", ")})`;
  // a tier applies where the base or no-base rule does: a base, or (no-base) a plain element
  const applies =
    utility.noBase === undefined
      ? `[style*="--${n}:"]`
      : `:is([style*="--${n}:"], :not(${[...primitives, ...(utility.noBaseExclude ?? [])].join(", ")}))`;
  const raw = utility.properties.map((property) => `  ${property}: var(--_${n}-resolved);`);
  const typed = utility.properties.map((property) =>
    utility.mode === "dual"
      ? `  ${property}: calc(var(--_${n}-len) + var(--_${n}-num) * var(--spacing));`
      : `  ${property}: ${emission(utility, `var(--_${n}-resolved)`)};`,
  );
  const lines = [`:where(${forms("")}) {`, ...raw, `}`];
  for (const tier of tiers) {
    lines.push(
      `${breakpointQuery(tier as Breakpoint)} {`,
      `  :where(${applies}[style*="--${n}--${tier}:"]) {`,
      ...typed.map((line) => `  ${line}`),
      `  }`,
      `  :where(${applies}${forms(tier)}) {`,
      ...raw.map((line) => `  ${line}`),
      `  }`,
      `}`,
    );
  }
  lines.push(``);
  return lines.join("\n");
}

/**
 * Keyword shorthands (`utility.aliases`): one exact-value rule per keyword that
 * rewrites the layer variable, at the base and at every tier, each placed where
 * that tier's setter is (a breakpoint's container query, a state's pseudo-class
 * and its group form, `@starting-style`, or behind the stuck switch). The family
 * file loads after the tier setters, so each rule overrides the raw copy.
 */
export function aliasRules(utility: Utility, tiers: readonly string[]): string {
  const n = utility.name;
  const aliases = Object.entries(utility.aliases ?? {});
  if (aliases.length === 0) return "";
  const each = (gate: (keyword: string) => string, layer: string, value = (v: string) => v) =>
    aliases.map(([keyword, v]) => `:where(${gate(keyword)}) { --_${layer}: ${value(v)}; }`);
  const lines = each((k) => `[style*="--${n}: ${k}"]`, n);
  const indent = (body: string[]) => body.map((line) => `  ${line}`);
  for (const tier of tiers) {
    const own = (k: string) => `[style*="--${n}--${tier}: ${k}"]`;
    if (!isState(tier)) {
      lines.push(
        `${breakpointQuery(tier as Breakpoint)} {`,
        ...indent(each(own, `${n}-${tier}`)),
        `}`,
      );
      continue;
    }
    const { pseudo, media, stuck, starting } = STATE_SELECTORS[tier];
    if (starting) {
      lines.push(`@starting-style {`, ...indent(each(own, `${n}-${tier}`)), `}`);
    } else if (stuck) {
      lines.push(...each(own, `${n}-${tier}`, (v) => `var(--_stuck-on) ${v}`));
    } else {
      // the pseudo-class first: it is a flag test, the substring scans the attribute
      const body = [
        ...each((k) => `${pseudo}${own(k)}`, `${n}-${tier}`),
        ...each(
          (k) => `[data-ui~="group"]${pseudo} [style*="--group-${n}--${tier}: ${k}"]`,
          `${n}-g-${tier}`,
        ),
      ];
      lines.push(...(media ? [`@media ${media} {`, ...indent(body), `}`] : body));
    }
  }
  return lines.join("\n") + "\n";
}

/**
 * The `--display` shorthands: `flex-col` and friends set the display and the
 * flex direction together, at the base and at each breakpoint, so a tier that
 * names any display resets the direction to row unless it is a shorthand. The
 * direction resolves through its own channel (`--_flex-direction-*`, what the
 * field primitive reads), emitted only on elements that use a shorthand.
 */
export function displayShorthandRules(): string {
  const entries = Object.entries(DISPLAY_SHORTHANDS);
  const block = (tier: string) => {
    const suffix = tier ? `--${tier}` : "";
    const layer = tier ? `-${tier}` : "";
    return [
      `:where([style*="--display${suffix}:"]) { --_flex-direction${layer}: row; }`,
      ...entries.map(
        ([keyword, [display, direction]]) =>
          `:where([style*="--display${suffix}: ${keyword}"]) { --_display${layer}: ${display}; --_flex-direction${layer}: ${direction}; }`,
      ),
    ];
  };
  const lines = block("");
  for (const bp of BREAKPOINTS) {
    lines.push(`${breakpointQuery(bp)} {`, ...block(bp).map((line) => `  ${line}`), `}`);
  }
  lines.push(
    `:where([style*="flex-row"], [style*="flex-col"]) {`,
    `  --_flex-direction-resolved: ${chain("flex-direction", [...BREAKPOINTS].reverse(), "var(--_flex-direction)")};`,
    `  flex-direction: var(--_flex-direction-resolved);`,
    `}`,
  );
  return lines.join("\n") + "\n";
}

/**
 * The border shorthand's channels. Each typed channel takes the
 * resolved value; one whose syntax the value does not match falls back to its
 * initial value at computed-value time, so exactly one of the flags is 1 for a
 * number or a length, and both are 0 for a color.
 */
function borderChannels(n: string): string[] {
  const resolved = `var(--_${n}-resolved)`;
  const isColor = `(1 - var(--_${n}-is-num) - var(--_${n}-is-len))`;
  return [
    `--_${n}-len: ${resolved};`,
    `--_${n}-num: ${resolved};`,
    `--_${n}-is-len: calc(sin(atan2(${resolved}, 1px)) * 0 + 1);`,
    `--_${n}-is-num: calc(${resolved} * 0 + 1);`,
    `--_${n}-clr: ${resolved};`,
    `--_${n}-w: calc(abs(var(--_${n}-len)) + abs(var(--_${n}-num)) * 1px + ${isColor} * 1px);`,
    `--_${n}-c: color-mix(in oklch, var(--_${n}-clr) calc(${isColor} * 100%), var(--color-border));`,
  ];
}

/**
 * One rule per physical side, gated on any shorthand covering it.
 * Precedence: the all-sides longhand, then the side, axis, and all-sides
 * shorthands. Style defaults to solid unless `--border-style` is set.
 */
export function borderSideRules(): string {
  const out: string[] = [];
  for (const { property, shorthands } of BORDER_SIDES) {
    const fallback = (part: "w" | "c") =>
      shorthands.reduceRight<string>(
        (inner, name) => (inner ? `var(--_${name}-${part}, ${inner})` : `var(--_${name}-${part})`),
        "",
      );
    const longhand = (kind: "width" | "color", part: "w" | "c") =>
      `var(--_border-${kind}-resolved, ${fallback(part)})`;
    out.push(
      `:where(${[...shorthands]
        .reverse()
        .map((name) => `[style*="--${name}:"]`)
        .join(", ")}) {`,
      `  ${property}-width: ${longhand("width", "w")};`,
      `  ${property}-style: var(--_border-style-resolved, solid);`,
      `  ${property}-color: ${longhand("color", "c")};`,
      `}`,
    );
  }
  return out.join("\n") + "\n";
}

/** The value a utility's property is set to, given the resolved value expression. */
function emission(utility: Utility, resolved: string): string {
  if (utility.emit === "repeat") return `repeat(${resolved}, minmax(0, 1fr))`;
  if (utility.emit === "span") return `span ${resolved} / span ${resolved}`;
  if (utility.emit === "grid-fit") return `repeat(auto-fit, minmax(min(${resolved}, 100%), 1fr))`;
  if (utility.emit === "bg")
    return `oklch(from ${resolved} l c h / calc(alpha * var(--_bg-alpha-resolved, 1)))`;
  return resolved;
}

/** Declarations that ride along with a utility's emission (compound utilities). */
function companions(utility: Utility): { before: string[]; after: string[] } {
  if (utility.emit === "line-clamp") {
    return {
      before: ["display: -webkit-box;", "-webkit-box-orient: vertical;"],
      after: ["overflow: hidden;"],
    };
  }
  return { before: [], after: [] };
}

/**
 * The no-base rule for an allowlisted utility: gated on any tier, the
 * chain ends in the CSS initial value as a literal, primitives excluded.
 */
export function noBaseRule(utility: Utility, primitives: readonly string[]): string {
  const n = utility.name;
  if (utility.noBase === undefined) return "";
  const excluded = [...primitives, ...(utility.noBaseExclude ?? [])].join(", ");
  const resolved = `var(--_${n}-resolved, ${utility.noBase})`;
  const body =
    utility.mode === "dual"
      ? [
          `  --_${n}-len: ${resolved};`,
          `  --_${n}-num: ${resolved};`,
          ...utility.properties.map(
            (property) =>
              `  ${property}: calc(var(--_${n}-len) + var(--_${n}-num) * var(--spacing));`,
          ),
        ]
      : utility.properties.map((property) => `  ${property}: ${emission(utility, resolved)};`);
  return [
    `:where(:is([style*="--${n}:"], [style*="--${n}--"], [style*="--group-${n}--"]):not(${excluded})) {`,
    ...body,
    `}`,
    ``,
  ].join("\n");
}

/** One tier's setter: gated generically, copies every utility of that tier into its layer variable. */
export function setterRule(tier: string, utilities: readonly Utility[]): string {
  const inTier = utilities.filter((utility) => tiersOf(utility).includes(tier));
  const indent = (lines: string[], depth: number) => lines.map((line) => " ".repeat(depth) + line);
  if (isState(tier) && STATE_SELECTORS[tier].stuck) return stuckSetter(tier, inTier);
  if (isState(tier) && STATE_SELECTORS[tier].starting) {
    // @starting-style applies only in the style an element transitions from (first
    // render, or leaving display: none); the starting layer variable heads every
    // chain, so the utility resolves to --<utility>--starting there and to its
    // usual value after, and a --transition animates between the two.
    const body = [
      `:where([style*="--${tier}:"]) {`,
      ...inTier.map((utility) => `  --_${utility.name}-${tier}: var(--${utility.name}--${tier});`),
      `}`,
    ];
    return [`@starting-style {`, ...indent(body, 2), `}`, ``].join("\n");
  }
  if (isState(tier)) {
    const { pseudo, media } = STATE_SELECTORS[tier];
    // The pseudo-class before the gate: Blink tests a compound's simple selectors
    // in source order, the pseudo-class is a flag read, and the substring scans
    // the whole attribute (every [style*=] rule is tested on every styled element).
    const own = [
      `:where(${pseudo}[style*="--${tier}:"]) {`,
      ...inTier.map((utility) => `  --_${utility.name}-${tier}: var(--${utility.name}--${tier});`),
      `}`,
    ];
    const group = [
      `:where([data-ui~="group"]${pseudo} [style*="--group-"]) {`,
      ...inTier.map(
        (utility) => `  --_${utility.name}-g-${tier}: var(--group-${utility.name}--${tier});`,
      ),
      `}`,
    ];
    const body = [...own, ...group];
    return (media ? [`@media ${media} {`, ...indent(body, 2), `}`] : body).concat("").join("\n");
  }
  const body = [
    `:where([style*="--${tier}:"]) {`,
    ...inTier.map((utility) => `  --_${utility.name}-${tier}: var(--${utility.name}--${tier});`),
    `}`,
  ];
  return [`${breakpointQuery(tier as Breakpoint)} {`, ...indent(body, 2), `}`, ``].join("\n");
}

/**
 * The stuck state's setter (`_utilities-tier-stuck.css`). Every sticky element
 * (or one with `--stuck-state`) becomes a scroll-state container and publishes
 * the side it tracks as `--_stuck-side` (its `--stuck-state`, else the fallback
 * side); the reset's sectioning elements keep their inline-size container beside
 * it. A container condition cannot read `var()`, and a container query only
 * reaches descendants, so each side is one query, `scroll-state(stuck: <side>)
 * and style(--_stuck-side: <side>)`, both evaluated on the nearest scroll-state
 * container, switching on `--_stuck-on` for the `--<utility>--stuck` readers.
 * Where container scroll-state queries are unsupported, `base/scroll-state.ts`
 * writes the stuck sides to the container's `data-ui-stuck`; the container
 * then publishes the inherited `--_stuck-polyfill` (empty when stuck to its
 * side, guaranteed-invalid otherwise, reset on every container so a nested one
 * does not inherit its parent's) and the readers copy it. One rule then copies
 * every utility behind the switch (`var(--_stuck-on) var(--bg--stuck)`):
 * registered, not inheriting, and guaranteed-invalid by default, so with it off
 * the layer variable is invalid and the chain falls through.
 *
 * No reader rule names the container: a `[style*=…]` in an ancestor compound
 * would make every inline style change invalidate every styled descendant.
 */
function stuckSetter(tier: string, inTier: readonly Utility[]): string {
  const { modifier, supports, polyfill, fallback, sticky, sides } = STUCK_STATE;
  const containers = `${sticky}, [style*="--${modifier}:"]`;
  const container = (side: string) =>
    side === fallback
      ? `:is([style*="--${modifier}: ${side}"], ${sticky}:not([style*="--${modifier}:"]))`
      : `[style*="--${modifier}: ${side}"]`;
  const reader = `[style*="--${tier}:"]`;
  const lines = [
    `@supports ${supports} {`,
    `  :where(${containers}) {`,
    `    container-type: scroll-state;`,
    `    --_stuck-side: var(--${modifier}, ${fallback});`,
    `  }`,
    `  :where(header, footer, section, article, main, ui-layout > *, [data-ui~="layout"] > *):where(${containers}) {`,
    `    container-type: inline-size scroll-state;`,
    `  }`,
  ];
  for (const side of sides) {
    lines.push(
      `  @container scroll-state(stuck: ${side}) and style(--_stuck-side: ${side}) {`,
      `    :where(${reader}) {`,
      `      --_stuck-on: ;`,
      `    }`,
      `  }`,
    );
  }
  lines.push(
    `}`,
    `@supports not ${supports} {`,
    `  :where(${containers}) {`,
    `    --_stuck-polyfill: initial;`,
    `  }`,
  );
  for (const side of sides) {
    lines.push(
      `  :where(${container(side)}[${polyfill}~="${side}"]) {`,
      `    --_stuck-polyfill: ;`,
      `  }`,
    );
  }
  lines.push(
    `  :where(${reader}) {`,
    `    --_stuck-on: var(--_stuck-polyfill);`,
    `  }`,
    `}`,
    `:where(${reader}) {`,
    ...inTier.map(
      (utility) =>
        `  --_${utility.name}-${tier}: var(--_stuck-on) var(--${utility.name}--${tier});`,
    ),
    `}`,
    ``,
  );
  return lines.join("\n");
}

/**
 * The effects composite: ring and shadow share one `box-shadow`,
 * behind the `--_focus-ring` a primitive publishes on `:focus-visible`. Every
 * chain in it already ends in a literal, so the composite is also the
 * no-base rule for these utilities: a second copy gated on any tier, primitives
 * excluded.
 */
export function compositeRule(
  utilities: readonly Utility[],
  primitives: readonly string[],
): string {
  const names = new Set(utilities.map((utility) => utility.name));
  const RING = ["shadow", "ring", "ring-color", "ring-offset", "ring-offset-color"];
  if (!RING.some((name) => names.has(name))) return "";
  const gate = (prefix: string, suffix: string) =>
    `:is(${RING.map((name) => `[style*="--${prefix}${name}${suffix}"]`).join(", ")})`;
  const excluded = primitives.join(", ");
  const offset = "var(--_ring-offset-resolved, 0px)";
  const emission = `  box-shadow: var(--_focus-ring, 0 0 #0000), 0 0 0 ${offset} var(--_ring-offset-color-resolved, transparent), 0 0 0 calc(${offset} + var(--_ring-resolved, 0px)) var(--_ring-color-resolved, var(--color-ring)), var(--_shadow-resolved, 0 0 #0000);`;
  return [
    `:where(${gate("", ":")}) {`,
    emission,
    `}`,
    `:where(:is(${gate("", "--")}, ${gate("group-", "--")}):not(${excluded})) {`,
    emission,
    `}`,
    ``,
  ].join("\n");
}

/**
 * Gradients: each `--bg-<type>` composes `background-image` from its prelude and
 * the shared `--bg-stops`. One rule per type, gated on the type's base; with
 * several types on one element the last in source (conic) wins.
 */
export function gradientRules(): string {
  return (
    GRADIENT_TYPES.map((type) =>
      [
        `:where([style*="--bg-${type}:"]) {`,
        `  background-image: ${type}-gradient(var(--_bg-${type}-resolved), var(--_bg-stops-resolved));`,
        `}`,
      ].join("\n"),
    ).join("\n") + "\n"
  );
}

/**
 * `--bg: none` clears the background: the color falls out on its own (`none`
 * is not a color, so the `--bg` emission is invalid and resolves to
 * transparent, in a primitive too), and these rules drop background-image at the
 * base and at each state tier. After the gradient rules, so `none` wins; lowest
 * precedence first (group states, then own states), as in the resolver chain.
 */
export function bgNoneRules(): string {
  const out = [`:where([style*="--bg: none"]) {`, `  background-image: none;`, `}`];
  // breakpoints ascend, then states (a state beats a breakpoint)
  for (const bp of BREAKPOINTS) {
    out.push(
      `${breakpointQuery(bp)} {`,
      `  :where([style*="--bg--${bp}: none"]) {`,
      `    background-image: none;`,
      `  }`,
      `}`,
    );
  }
  // the scroll state has no pseudo-class to gate on; its color still falls out
  const ascending = [...STATES].reverse().filter(hasGroup);
  const rule = (selector: string) => [`:where(${selector}) {`, `  background-image: none;`, `}`];
  for (const [group, states] of [
    [true, ascending],
    [false, ascending],
  ] as const) {
    for (const tier of states) {
      const { pseudo, media } = STATE_SELECTORS[tier];
      const body = group
        ? rule(`[data-ui~="group"]${pseudo} [style*="--group-bg--${tier}: none"]`)
        : rule(`${pseudo}[style*="--bg--${tier}: none"]`);
      out.push(...(media ? [`@media ${media} {`, ...body.map((l) => `  ${l}`), `}`] : body));
    }
  }
  return out.join("\n") + "\n";
}

/**
 * A pseudo-element rule: exact gate on `--<side>-<utility>`, read
 * straight from the (unregistered, inherited) utility on the pseudo-element.
 */
export function pseudoRule(utility: Utility, side: PseudoSide): string {
  if (!utility.pseudo || utility.emit === "none") return "";
  const n = `${side}-${utility.name}`;
  const lines = [`:where([style*="--${n}:"])::${side} {`];
  if (utility.mode === "dual") {
    lines.push(`  --_${n}-len: var(--${n});`, `  --_${n}-num: var(--${n});`);
    for (const property of utility.properties) {
      lines.push(`  ${property}: calc(var(--_${n}-len) + var(--_${n}-num) * var(--spacing));`);
    }
  } else {
    const value =
      utility.emit === "bg"
        ? `oklch(from var(--${n}) l c h / calc(alpha * var(--${side}-bg-alpha, 1)))`
        : `var(--${n})`;
    for (const property of utility.properties) lines.push(`  ${property}: ${value};`);
  }
  lines.push(`}`, ``);
  return lines.join("\n");
}

/** Typed pairs for dual utilities on pseudo-elements; declared on the pseudo-element itself. */
function pseudoRegistrations(utility: Utility): string {
  if (!utility.pseudo || utility.mode !== "dual") return "";
  return PSEUDO_SIDES.map(
    (side) =>
      register(`_${side}-${utility.name}-len`, '"<length-percentage>"', "0px") +
      register(`_${side}-${utility.name}-num`, '"<number>"', "0"),
  ).join("");
}

/**
 * `_breakpoints.css`: the layout width tokens (the bands and the component
 * sizes that follow them, in rem). The breakpoint tiers are separate: they query
 * the nearest inline-size container in ch (`_utilities-tier-<breakpoint>.css`).
 * Comments in every generated file stay to a few words: `src/index.css` ships
 * them raw to zero-build pages, and the explanations live here.
 */
function breakpointsFile(): string {
  return [
    BANNER,
    "/* Layout widths (rem) */",
    "@layer variables {",
    "  :root {",
    ...BREAKPOINTS.map((bp) => `    --layout-${bp}: ${LAYOUT_REM[bp]}rem;`),
    "  }",
    "}",
    "",
  ].join("\n");
}

function familyFile(
  family: Family,
  utilities: readonly Utility[],
  primitives: readonly string[],
): string {
  const rules = utilities
    .map(
      (utility) =>
        baseRule(utility, tiersOf(utility)) +
        noBaseRule(utility, primitives) +
        keywordRules(utility, tiersOf(utility), primitives) +
        aliasRules(utility, tiersOf(utility)) +
        (utility.name === "display" ? displayShorthandRules() : ""),
    )
    .concat(compositeRule(utilities, primitives))
    .concat(utilities.some((utility) => utility.emit === "border") ? [borderSideRules()] : [])
    .concat(
      utilities.some((utility) => utility.name === "bg-stops")
        ? [gradientRules(), bgNoneRules()]
        : [],
    )
    .join("\n")
    .replace(/^(?=.)/gm, "  ");
  return `${BANNER}\n/* ${family} family */\n@layer ui.utilities {\n${rules}}\n`;
}

/**
 * Every primitive, as the selectors the no-base, composite, and keyword rules
 * exclude: each tag form plus each `data-ui` identity a primitive stylesheet
 * selects (`[data-ui~="button"]`). A primitive owns its properties (a disabled
 * button's opacity, a card's gap), so a tier-only utility there needs a base.
 * Typography roles, switches, and prose live in `src/base/`, so an element that
 * carries only those (`data-ui="text-2xl"`, `data-ui="group"`) is plain here.
 */
export function primitiveSelectors(
  dir = join(dirname(fileURLToPath(import.meta.url)), "..", "src", "primitives"),
): string[] {
  const tokens = new Set<string>();
  for (const name of readdirSync(dir)) {
    for (const file of readdirSync(join(dir, name)).filter((f) => f.endsWith(".css"))) {
      const css = readFileSync(join(dir, name, file), "utf8");
      for (const m of css.matchAll(/\[data-ui~="([a-z0-9-]+)"\]/g)) tokens.add(m[1]!);
    }
  }
  return [...TAG_FORMS, ...[...tokens].sort().map((token) => `[data-ui~="${token}"]`)];
}

/** Every generated file, keyed by its name under `src/base/`. */
export function generate(
  utilities: readonly Utility[] = UTILITIES,
  primitives: readonly string[] = primitiveSelectors(),
): Map<string, string> {
  const files = new Map<string, string>();
  files.set("_breakpoints.css", breakpointsFile());
  // The stuck state's privates (see stuckSetter): the switch the readers copy,
  // the side a container tracks (typed, so the style() query compares idents and
  // a bad side falls back), the polyfill's inherited flag, and --stuck-state
  // itself, non-inheriting like every utility so a nested container reads its own.
  const stuckRegistrations =
    register("_stuck-on") +
    register("_stuck-side", `"${STUCK_STATE.sides.join(" | ")}"`, STUCK_STATE.fallback) +
    register("_stuck-polyfill", undefined, undefined, true) +
    register(STUCK_STATE.modifier);
  files.set(
    "_properties.css",
    `${BANNER}\n/* Registrations: utility, layer variable, resolver, dual pair */\n${utilities.map(registrations).join("")}\n/* Dual pairs on pseudo-elements */\n${utilities.map(pseudoRegistrations).join("")}\n/* Focus ring, published by primitives */\n${register("_focus-ring")}\n/* Stuck state */\n${stuckRegistrations}\n/* --display shorthands' flex-direction channel */\n${["", ...BREAKPOINTS.map((bp) => `-${bp}`), "-resolved"].map((suffix) => register(`_flex-direction${suffix}`)).join("")}`,
  );
  for (const tier of [...BREAKPOINTS, ...STATES]) {
    const inTier = utilities.filter((utility) => tiersOf(utility).includes(tier));
    files.set(
      `_properties-${tier}.css`,
      `${BANNER}\n/* ${tier} tier registrations */\n${inTier.map((utility) => tierRegistrations(utility, tier)).join("")}`,
    );
  }
  for (const tier of [...BREAKPOINTS, ...STATES]) {
    files.set(
      `_utilities-tier-${tier}.css`,
      `${BANNER}\n/* ${tier} tier setter */\n@layer ui.utilities {\n${setterRule(tier, utilities).replace(/^(?=.)/gm, "  ")}}\n`,
    );
  }
  const families = [...new Set(utilities.map((utility) => utility.family))];
  for (const family of families) {
    files.set(
      `_utilities-${family}.css`,
      familyFile(
        family,
        utilities.filter((utility) => utility.family === family),
        primitives,
      ),
    );
  }
  const pseudo = [...utilities, ...PSEUDO_ONLY]
    .flatMap((utility) => PSEUDO_SIDES.map((side) => pseudoRule(utility, side)))
    .filter(Boolean)
    .join("\n")
    .replace(/^(?=.)/gm, "  ");
  files.set(
    "_utilities-pseudo.css",
    `${BANNER}\n/* Pseudo-element utilities (--before-, --after-) */\n@layer ui.utilities {\n${pseudo}}\n`,
  );
  return files;
}

export function main(): void {
  const base = join(dirname(fileURLToPath(import.meta.url)), "..", "src", "base");
  for (const [file, text] of generate()) {
    writeFileSync(join(base, file), text);
    console.log(`wrote src/base/${file}`);
  }
}

if (import.meta.main) main();
