/**
 * @fileoverview Zazz — single entry point for every component script.
 * @description Imports all Zazz behavior modules so a page needs only one
 * `<script type="module" src=".../index.js">` instead of ten separate tags.
 * Each module runs for its side effects: global/utility setup, scroll-reveal
 * and carousel auto-initialization, SPA navigation, and the custom-element
 * registrations (`<ui-autocomplete>`, `<ui-carousel>`, `<ui-combobox>`,
 * `<ui-command>`, `<ui-lightbox>`, `<ui-menu>`, `<ui-password>`, `<ui-tabs>`,
 * `<ui-toaster>`).
 *
 * Internal dependencies are resolved by the module graph — utils loads
 * before embla, embla before carousel, carousel before lightbox — so the
 * import order below is for readability, not correctness.
 *
 * External dependencies (signal-polyfill, the Embla packages) are imported by
 * bare specifier and resolved by the page's import map — generated by
 * `head.ts` with pinned, SRI-checked jsDelivr URLs. No extra script tags.
 */
import "./base/utils.js";
import "./base/reveal.js";
import "./base/dialog-lifecycle.js";
import "./base/embla.js";
import "./primitives/autocomplete/autocomplete.js";
import "./primitives/combobox/combobox.js";
import "./primitives/command/command.js";
import "./primitives/carousel/carousel.js";
import "./primitives/lightbox/lightbox.js";
import "./primitives/menu/menu.js";
import "./primitives/otp/otp.js";
import "./primitives/password-group/password-group.js";
import "./primitives/select/multiselect.js";
import "./primitives/tabs/tabs.js";
import "./primitives/toaster/toaster.js";
import "./base/navigation.js";
