/**
 * @fileoverview Generates `syntaxes/zazz.injection.tmLanguage.json`: a TextMate
 * grammar injected into HTML that scopes Zazz names, so any theme colors them
 * before the language server starts. Built from the utility table and the
 * editor data; `generate-grammar.test.ts` keeps the committed file fresh.
 *
 * Inside `style=""`: utility names (by family), tier suffixes, `group-` and
 * pseudo-side prefixes, `--ui-*` hooks, and modifiers. Inside `data-ui=""`:
 * the kit's identity tokens. Unknown names keep the CSS grammar's scopes (the
 * server reports them).
 */

import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import {
  BREAKPOINTS,
  PSEUDO_ONLY,
  PSEUDO_SIDES,
  STATES,
  STUCK_STATE,
  UTILITIES,
  type Utility,
} from "@zazz-ui/core/base/utilities.ts";
import htmlData from "@zazz-ui/core/editor/zazz.html-data.json" with { type: "json" };

export const GRAMMAR_PATH = fileURLToPath(
  new URL("../syntaxes/zazz.injection.tmLanguage.json", import.meta.url),
);

/** Alternation of literal words, longest first so a prefix never wins early. */
function alternation(words: Iterable<string>): string {
  return [...new Set(words)]
    .sort((a, b) => b.length - a.length || a.localeCompare(b))
    .map((word) => word.replace(/[.*+?^${}()|[\]\\]/g, "\\$&"))
    .join("|");
}

export function generateGrammar(): object {
  const tiers = alternation([...BREAKPOINTS, ...STATES]);
  const sides = alternation(PSEUDO_SIDES.map((side) => `${side}-`));
  const byFamily = new Map<string, Utility[]>();
  for (const utility of [...UTILITIES, ...PSEUDO_ONLY]) {
    byFamily.set(utility.family, [...(byFamily.get(utility.family) ?? []), utility]);
  }
  const utilityPatterns = [...byFamily].map(([family, utilities]) => ({
    match: `(--)(group-)?(${sides})?(${alternation(utilities.map((u) => u.name))})(?:(--)(${tiers}))?(?=\\s*:)`,
    captures: {
      1: { name: "punctuation.definition.custom-property.css.zazz" },
      2: { name: "storage.modifier.group.zazz" },
      3: { name: "entity.other.attribute-name.pseudo-element.css.zazz" },
      4: { name: `support.type.property-name.css.zazz.utility.${family}` },
      5: { name: "punctuation.separator.tier.zazz" },
      6: { name: "entity.other.attribute-name.pseudo-class.css.zazz.tier" },
    },
  }));
  const identities = (
    htmlData.globalAttributes.find((attribute) => attribute.name === "data-ui")?.values ?? []
  ).map((value) => value.name);
  return {
    $schema: "https://raw.githubusercontent.com/martinring/tmlanguage/master/tmlanguage.json",
    scopeName: "zazz.injection",
    comment: "Generated by packages/vscode/scripts/generate-grammar.ts — do not edit.",
    injectionSelector: "L:meta.attribute.style.html, L:meta.attribute.data-x.data-ui.html",
    patterns: [{ include: "#style" }, { include: "#identities" }],
    repository: {
      style: {
        patterns: [
          {
            match: "(--ui-[a-z0-9-]+)(?=\\s*:)",
            captures: { 1: { name: "variable.other.constant.zazz.hook" } },
          },
          {
            match: `(--${alternation([STUCK_STATE.modifier])})(?=\\s*:)`,
            captures: { 1: { name: "support.type.property-name.css.zazz.modifier" } },
          },
          ...utilityPatterns,
        ],
      },
      identities: {
        patterns: [
          {
            match: `(?<=["'\\s])(${alternation(identities)})(?=["'\\s])`,
            captures: { 1: { name: "support.class.zazz.identity" } },
          },
        ],
      },
    },
  };
}

export function grammarText(): string {
  return `${JSON.stringify(generateGrammar(), null, 2)}\n`;
}

if (import.meta.main) {
  writeFileSync(GRAMMAR_PATH, grammarText());
  console.log("wrote syntaxes/zazz.injection.tmLanguage.json");
}
