"use strict";

/**
 * @fileoverview `zazz.json` — the project's vendoring provenance record.
 * @description One file at the project root records what was vendored, from
 * which kit version, and the sha256 of each file's pristine published bytes
 * at vendor time (never the on-disk state, so edits stay detectable forever —
 * ADR-0009). Every command loads it by walking up from the cwd, and every
 * successful transaction rewrites it exactly once.
 */

import { readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { ZazzError } from "./errors.ts";

export const CONFIG_NAME = "zazz.json";
export const SCHEMA_URL = "https://zazz.sh/schema.json";

export interface FileHashes {
  [srcRelPath: string]: string; // "sha256-<base64>" of pristine bytes at vendor time
}

export interface ZazzConfig {
  $schema: string;
  /** The kit version the project tracks, and its tarball integrity. */
  kit: { version: string; integrity: string };
  /** Vendor target directory, posix-relative to zazz.json's directory. */
  dir: string;
  /** Vendored script language; every command honors it. */
  language: "js" | "ts";
  /** Stylesheet wired into layer(legacy), or null. */
  legacy: string | null;
  /** Head options that must survive head.html regeneration. */
  head: { fonts: boolean; themeScript: boolean };
  /**
   * Base platform files (css layers, core runtime, and the CLI-generated
   * entries index.css/index.js/head.html — generated entries record the hash
   * of their generated bytes). `version` appears only when a narrowed update
   * has moved base files ahead of `kit.version`.
   */
  base: { version?: string; files: FileHashes };
  /** Vendored primitives with per-primitive provenance. */
  primitives: Record<string, { version: string; files: FileHashes }>;
}

/** Walks up from `cwd` to find the nearest zazz.json. */
export async function loadConfig(
  cwd: string,
): Promise<{ config: ZazzConfig; root: string } | null> {
  let dir = path.resolve(cwd);
  for (;;) {
    const file = path.join(dir, CONFIG_NAME);
    let raw: string;
    try {
      raw = await readFile(file, "utf8");
    } catch {
      const parent = path.dirname(dir);
      if (parent === dir) return null;
      dir = parent;
      continue;
    }
    let parsed: unknown;
    try {
      parsed = JSON.parse(raw);
    } catch (error) {
      throw new ZazzError(`${file} is not valid JSON: ${(error as Error).message}`);
    }
    return { config: validateConfig(parsed, file), root: dir };
  }
}

export async function saveConfig(root: string, config: ZazzConfig): Promise<void> {
  await writeFile(path.join(root, CONFIG_NAME), serializeConfig(config));
}

/** Stable key order so diffs of zazz.json stay readable. */
export function serializeConfig(config: ZazzConfig): string {
  const ordered: ZazzConfig = {
    $schema: config.$schema,
    kit: { version: config.kit.version, integrity: config.kit.integrity },
    dir: config.dir,
    language: config.language,
    legacy: config.legacy,
    head: { fonts: config.head.fonts, themeScript: config.head.themeScript },
    base: {
      ...(config.base.version !== undefined ? { version: config.base.version } : {}),
      files: sortKeys(config.base.files),
    },
    primitives: Object.fromEntries(
      Object.keys(config.primitives)
        .sort()
        .map((name) => {
          const entry = config.primitives[name];
          if (!entry) throw new ZazzError(`primitive entry vanished while saving: ${name}`);
          return [name, { version: entry.version, files: sortKeys(entry.files) }];
        }),
    ),
  };
  return `${JSON.stringify(ordered, null, 2)}\n`;
}

function sortKeys(files: FileHashes): FileHashes {
  return Object.fromEntries(Object.entries(files).sort(([a], [b]) => a.localeCompare(b)));
}

/** Structural validation with pointed messages; throws ZazzError. */
export function validateConfig(raw: unknown, source: string): ZazzConfig {
  const fail = (detail: string): never => {
    throw new ZazzError(`${source} is not a valid zazz config: ${detail}`, {
      hint: "if you edited it by hand, compare against a fresh `zazz-ui init` in an empty directory",
    });
  };
  if (typeof raw !== "object" || raw === null) fail("not an object");
  const config = raw as Record<string, unknown>;

  const kit = config.kit as Record<string, unknown> | undefined;
  if (typeof kit !== "object" || kit === null || typeof kit.version !== "string") {
    fail("kit.version missing");
  }
  if (typeof config.dir !== "string" || config.dir.length === 0) fail("dir missing");
  if (config.language !== "js" && config.language !== "ts") fail("language must be js or ts");
  if (config.legacy !== null && typeof config.legacy !== "string")
    fail("legacy must be a path or null");

  const head = config.head as Record<string, unknown> | undefined;
  if (
    typeof head !== "object" ||
    head === null ||
    typeof head.fonts !== "boolean" ||
    typeof head.themeScript !== "boolean"
  ) {
    fail("head.fonts / head.themeScript missing");
  }

  const base = config.base as Record<string, unknown> | undefined;
  if (typeof base !== "object" || base === null || !isFileHashes(base.files)) {
    fail("base.files missing");
  }
  if (base && base.version !== undefined && typeof base.version !== "string") {
    fail("base.version must be a string");
  }

  const primitives = config.primitives as Record<string, unknown> | undefined;
  if (typeof primitives !== "object" || primitives === null) fail("primitives missing");
  for (const [name, entry] of Object.entries(primitives as Record<string, unknown>)) {
    const record = entry as Record<string, unknown>;
    if (
      typeof record !== "object" ||
      record === null ||
      typeof record.version !== "string" ||
      !isFileHashes(record.files)
    ) {
      fail(`primitives.${name} is malformed`);
    }
  }

  return raw as ZazzConfig;
}

function isFileHashes(value: unknown): value is FileHashes {
  return (
    typeof value === "object" &&
    value !== null &&
    Object.values(value).every((hash) => typeof hash === "string")
  );
}
