"use strict";

/**
 * @fileoverview The three CLI-composed artifacts: `index.css`, `index.js`,
 * and `head.html`.
 * @description The entry files mirror the kit's own `src/index.css` /
 * `src/index.ts` anatomy so a vendored project reads like the kit teaches.
 * Rendering builds them whole (init); insertion mutates them surgically so
 * `add` works on user-edited entries — imports land at their cascade
 * position, anchored on existing primitive imports, the primitives section
 * marker, or the first post-base import, in that order. `head.html` is
 * CLI-owned and always rendered whole by the kit's own `buildHead`.
 */

import type { ZazzConfig } from "./config.ts";
import type { ResolvedKit } from "./kit.ts";
import type { Language } from "./plan.ts";
import { baseCssSplit, corePolyfills, coreRuntime, scriptVariants } from "./plan.ts";

/** The insertion anchor `add` looks for in an untouched index.css. */
export const PRIMITIVES_MARKER =
  "/* Zazz primitives — zazz-ui add inserts imports here in cascade order. */";

// Always a sublayer: rules imported into bare `legacy` form an implicit final
// sublayer that outranks `legacy.migrations` (see _layers.css).
const LEGACY_SLOT_COMMENT =
  '/* Legacy layer — import your legacy stylesheets into layer(legacy.imports) here: */\n/* @import "./your-legacy.css" layer(legacy.imports); */';

/** The v1 post-base anchor; newer kits pass `baseCssSplit(manifest).post[0]`. */
const V1_POST_ANCHOR = "base/_utilities.css";

/** Renders the vendored stylesheet entry (init; also repair regeneration). */
export function renderIndexCss(options: {
  kit: ResolvedKit;
  legacy: string | null;
  primitives: { name: string; css: string[] }[];
}): string {
  const { pre, post } = baseCssSplit(options.kit.manifest);

  const legacyBlock =
    options.legacy === null
      ? LEGACY_SLOT_COMMENT
      : `/* Legacy layer — existing styles cascade below the kit. */\n@import "${options.legacy}" layer(legacy.imports);`;

  const primitiveImports = options.primitives
    .flatMap((p) => p.css)
    .map((file) => `@import "./${file}";`)
    .join("\n");

  return `/**
 * index.css — vendored Zazz entry (generated by zazz-ui; yours to edit).
 * Order matters: _layers.css declares the cascade layers and must load first;
 * the post-primitive base files (utilities) stay the final normal override layer.
 */

/* base — order matters */
${pre.map((file) => `@import "./${file}";`).join("\n")}

${legacyBlock}

${PRIMITIVES_MARKER}
${primitiveImports}${primitiveImports ? "\n" : ""}
/* The generated utilities stay the final normal Zazz override layer. */
${post.map((file) => `@import "./${file}";`).join("\n")}
`;
}

/** Renders the vendored script entry (init). */
export function renderIndexJs(options: { kit: ResolvedKit; language: Language }): string {
  const runtime = coreRuntime(options.kit.manifest).map((jsPath) =>
    importLine(jsPath, options.language),
  );
  // Same gate as the kit's index.ts: browsers with the feature never fetch the polyfill.
  const gates = corePolyfills(options.kit.manifest).map(({ file, supports: [property, value] }) => {
    const [specifier] = scriptVariants(file, options.language);
    return `if (typeof CSS !== "undefined" && !CSS.supports("${property}", "${value}")) {\n  void import("./${specifier}");\n}`;
  });
  const polyfills =
    gates.length > 0
      ? `\n// Polyfills load only where the browser lacks the CSS feature.\n${gates.join("\n")}\n`
      : "";
  return `/**
 * index.js — vendored Zazz behavior entry (generated by zazz-ui; yours to edit).
 * zazz-ui add inserts primitive imports after the last import, in dependency order.
 */

${runtime.join("\n")}
${polyfills}`;
}

function importLine(jsPath: string, language: Language): string {
  const [file] = scriptVariants(jsPath, language);
  return `import "./${file}";`;
}

/**
 * @description Inserts primitive `@import` lines at their cascade position.
 * Idempotent: already-imported primitives are skipped. Works on user-edited
 * files — anchors, in order: the last existing primitive import with a lower
 * cascade position, the primitives marker, the first post-base import, end.
 */
export function insertCssImports(
  existing: string,
  additions: { name: string; css: string[] }[],
  cascadeOrder: string[],
  postAnchor: string = V1_POST_ANCHOR,
): string {
  const position = new Map(cascadeOrder.map((name, index) => [name, index]));
  const lines = existing.split("\n");

  const sorted = [...additions].sort(
    (a, b) => (position.get(a.name) ?? Infinity) - (position.get(b.name) ?? Infinity),
  );

  for (const addition of sorted) {
    if (addition.css.length === 0) continue;
    if (lines.some((line) => line.includes(`./primitives/${addition.name}/`))) continue;

    const newPosition = position.get(addition.name) ?? Infinity;
    let insertAt = -1;

    // After the last existing primitive import that precedes us in cascade order.
    for (const [index, line] of lines.entries()) {
      const match = /@import "\.\/primitives\/([a-z-]+)\//.exec(line);
      if (!match) continue;
      const existingPosition = position.get(match[1] ?? "") ?? Infinity;
      if (existingPosition < newPosition) insertAt = index + 1;
    }
    // Fallbacks: the marker, then just before the utilities/layout block.
    if (insertAt === -1) {
      const marker = lines.findIndex((line) => line.includes("Zazz primitives"));
      if (marker !== -1) insertAt = marker + 1;
    }
    if (insertAt === -1) {
      const post = lines.findIndex((line) => line.includes(postAnchor));
      insertAt = post !== -1 ? post : lines.length;
    }

    lines.splice(insertAt, 0, ...addition.css.map((file) => `@import "./${file}";`));
  }

  return lines.join("\n");
}

/**
 * @description Inserts missing script imports (base scripts and primitive
 * scripts, caller-ordered) after the entry's last static import, so they stay
 * above the polyfill gates; appends when there is none. Idempotent.
 */
export function appendJsImports(existing: string, jsPaths: string[], language: Language): string {
  const additions = jsPaths
    .map((jsPath) => importLine(jsPath, language))
    .filter((line) => !existing.includes(line));
  if (additions.length === 0) return existing;
  const lines = (existing.endsWith("\n") ? existing : `${existing}\n`).split("\n");
  // The last line of the last static import: a statement ends at its module
  // specifier, so a multi-line `import {\n  a,\n} from "./x.js";` ends on `} from …`.
  let lastImport = -1;
  for (let index = 0; index < lines.length; index++) {
    if (!/^import\s/.test(lines[index]!)) continue;
    while (index < lines.length - 1 && !/["'][^"']*["']\s*;?\s*$/.test(lines[index]!)) index++;
    lastImport = index;
  }
  // The trailing "" after the final newline: insert before it to append.
  lines.splice(lastImport === -1 ? lines.length - 1 : lastImport + 1, 0, ...additions);
  return lines.join("\n");
}

/** Renders head.html through the tarball's own buildHead. */
export function renderHead(kit: ResolvedKit, config: ZazzConfig): string {
  const head = kit.buildHead({
    base: `./${config.dir}`,
    fontDisplay: config.head.fonts ? "swap" : false,
    theme: config.head.themeScript,
  });
  return `<!-- head.html — generated by zazz-ui; regenerated on update. Paste into your <head>. -->\n${head}\n`;
}
