"use strict";

/**
 * @fileoverview The three CLI-composed artifacts: `index.css`, `index.js`,
 * and `head.html`.
 * @description The entry files mirror the kit's own `src/index.css` /
 * `src/index.ts` anatomy so a vendored project reads like the kit teaches.
 * Rendering builds them whole (init); insertion mutates them surgically so
 * `add` works on user-edited entries — imports land at their cascade
 * position, anchored on existing primitive imports, the primitives section
 * marker, or the `_utilities.css` import, in that order. `head.html` is
 * CLI-owned and always rendered whole by the kit's own `buildHead`.
 */

import type { ZazzConfig } from "./config.ts";
import type { ResolvedKit } from "./kit.ts";
import type { Language } from "./plan.ts";
import { baseCss, coreRuntime, scriptVariants } from "./plan.ts";

/** The insertion anchor `add` looks for in an untouched index.css. */
export const PRIMITIVES_MARKER =
  "/* Zazz primitives — zazz-ui add inserts imports here in cascade order. */";

const LEGACY_SLOT_COMMENT =
  '/* Legacy layer — import your legacy stylesheets into layer(legacy) here: */\n/* @import "./your-legacy.css" layer(legacy); */';

const PRE_BASE_COUNT = 5; // _layers … _view-transitions load before primitives
const POST_BASE_COUNT = 2; // _utilities + _layout stay the final override layer

/** Renders the vendored stylesheet entry (init; also repair regeneration). */
export function renderIndexCss(options: {
  kit: ResolvedKit;
  legacy: string | null;
  primitives: { name: string; css: string[] }[];
}): string {
  const base = baseCss(options.kit.manifest);
  const pre = base.slice(0, PRE_BASE_COUNT);
  const post = base.slice(base.length - POST_BASE_COUNT);

  const legacyBlock =
    options.legacy === null
      ? LEGACY_SLOT_COMMENT
      : `/* Legacy layer — existing styles cascade below the kit. */\n@import "${options.legacy}" layer(legacy);`;

  const primitiveImports = options.primitives
    .flatMap((p) => p.css)
    .map((file) => `@import "./${file}";`)
    .join("\n");

  return `/**
 * index.css — vendored Zazz entry (generated by zazz-ui; yours to edit).
 * Order matters: _layers.css declares the cascade layers and must load first;
 * _utilities.css and _layout.css stay the final normal override layer.
 */

/* base — order matters */
${pre.map((file) => `@import "./${file}";`).join("\n")}

${legacyBlock}

${PRIMITIVES_MARKER}
${primitiveImports}${primitiveImports ? "\n" : ""}
/* Utilities and layout remain the final normal Zazz override layer. */
${post.map((file) => `@import "./${file}";`).join("\n")}
`;
}

/** Renders the vendored script entry (init). */
export function renderIndexJs(options: { kit: ResolvedKit; language: Language }): string {
  const runtime = coreRuntime(options.kit.manifest).map((jsPath) =>
    importLine(jsPath, options.language),
  );
  return `/**
 * index.js — vendored Zazz behavior entry (generated by zazz-ui; yours to edit).
 * zazz-ui add appends primitive imports below in dependency order.
 */

${runtime.join("\n")}
`;
}

function importLine(jsPath: string, language: Language): string {
  const [file] = scriptVariants(jsPath, language);
  return `import "./${file}";`;
}

/**
 * @description Inserts primitive `@import` lines at their cascade position.
 * Idempotent: already-imported primitives are skipped. Works on user-edited
 * files — anchors, in order: the last existing primitive import with a lower
 * cascade position, the primitives marker, the first post-base import, end.
 */
export function insertCssImports(
  existing: string,
  additions: { name: string; css: string[] }[],
  cascadeOrder: string[],
): string {
  const position = new Map(cascadeOrder.map((name, index) => [name, index]));
  const lines = existing.split("\n");

  const sorted = [...additions].sort(
    (a, b) => (position.get(a.name) ?? Infinity) - (position.get(b.name) ?? Infinity),
  );

  for (const addition of sorted) {
    if (addition.css.length === 0) continue;
    if (lines.some((line) => line.includes(`./primitives/${addition.name}/`))) continue;

    const newPosition = position.get(addition.name) ?? Infinity;
    let insertAt = -1;

    // After the last existing primitive import that precedes us in cascade order.
    for (const [index, line] of lines.entries()) {
      const match = /@import "\.\/primitives\/([a-z-]+)\//.exec(line);
      if (!match) continue;
      const existingPosition = position.get(match[1] ?? "") ?? Infinity;
      if (existingPosition < newPosition) insertAt = index + 1;
    }
    // Fallbacks: the marker, then just before the utilities/layout block.
    if (insertAt === -1) {
      const marker = lines.findIndex((line) => line.includes("Zazz primitives"));
      if (marker !== -1) insertAt = marker + 1;
    }
    if (insertAt === -1) {
      const utilities = lines.findIndex((line) => line.includes("base/_utilities.css"));
      insertAt = utilities !== -1 ? utilities : lines.length;
    }

    lines.splice(insertAt, 0, ...addition.css.map((file) => `@import "./${file}";`));
  }

  return lines.join("\n");
}

/**
 * @description Appends missing script imports (base scripts and primitive
 * scripts, caller-ordered) to the script entry. Idempotent.
 */
export function appendJsImports(existing: string, jsPaths: string[], language: Language): string {
  const additions = jsPaths
    .map((jsPath) => importLine(jsPath, language))
    .filter((line) => !existing.includes(line));
  if (additions.length === 0) return existing;
  const body = existing.endsWith("\n") ? existing : `${existing}\n`;
  return `${body}${additions.join("\n")}\n`;
}

/** Renders head.html through the tarball's own buildHead. */
export function renderHead(kit: ResolvedKit, config: ZazzConfig): string {
  const head = kit.buildHead({
    base: `./${config.dir}`,
    fontDisplay: config.head.fonts ? "swap" : false,
    theme: config.head.themeScript,
  });
  return `<!-- head.html — generated by zazz-ui; regenerated on update. Paste into your <head>. -->\n${head}\n`;
}
